name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
      - name: setting up node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name:  installing dependecies using npm
        run: npm install -g yarn
      - name: intalling using yarn
        run: yarn install --frozen-lockfile
      - name: building the application
        run: yarn build
      - name: configure s3 crendentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: sync files with s3
        run: aws s3 sync ./build s3://risk-form
      - name: invalidate cloudfront cdn
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.CDN_DISTRIBUTION_ID}} --paths "/*"
     
